name: MedievalFactions
version: 3.6.2
author: KingdomProgrammers
main: dansplugins.factionsystem.MedievalFactions
api-version: 1.13

commands:
  mf:
  f:
  medievalfactions:
  factions:

permissions:
  mf.claim:
    default: true
  mf.unclaim:
    default: true
  mf.unclaimall:
    default: true
  mf.checkclaim:
    default: true
  mf.autoclaim:
    default: true
  mf.version:
    default: true
  mf.unclaim.others:
  mf.resetpowerlevels:
